name: moon-audio

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup-moonbit@v1
      - run: moon check
      - run: moon test
